## Numpy Library Exercises

In [1]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [2]:
# let it be an array of 10 random integers between 0 and 10
array = np.random.randint(low=0, high=10, size=10, dtype=int)
print(array)

# change the sign of elements whose values ​​are between 3 and 8
array = np.where((array > 3) & (array < 8), -array, array)
print(array)

[3 8 2 1 6 6 8 8 7 6]
[ 3  8  2  1 -6 -6  8  8 -7 -6]


**2.** Replace the maximum element of a random array with 0

In [3]:
# let it be an array of 10 random integers between 0 and 10
array = np.random.randint(low=0, high=10, size=10, dtype=int)
print(array)

# find the maximum element and replace it with 0
print(array.argmax())
array[array.argmax()] = 0
print(array)

[5 2 6 8 6 7 8 0 9 3]
8
[5 2 6 8 6 7 8 0 0 3]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [4]:
# input a 2-dim array
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

# construct the direct product of arrays
grid = np.meshgrid(array[0], array[1], indexing='ij')
print(grid)
direct_product = np.prod(grid, axis=0)
print(f"\nDirect product:\n{direct_product}")

[[1 2 3]
 [4 5 6]]
(array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]]), array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]]))

Direct product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [ ]:
# complexity: speed = O(n^2), memory = O(n)

# generate two arrays
A = np.random.randint(low=0, high=5, size=(8, 3), dtype=int)
B = np.random.randint(low=0, high=5, size=(2, 2), dtype=int)
print(A)
print(B)

# find rows in A that contain elements from each row in B, regardless of the order of the elements in B
print("-" * 20)
for row in A:
    checked_fows = np.isin(B, row)
    if checked_fows.any(axis=1).all():
        print(row)


[[4 3 1]
 [4 4 2]
 [3 2 3]
 [2 2 3]
 [2 4 4]
 [3 4 4]
 [0 1 4]
 [1 1 1]]
[[2 3]
 [1 4]]
--------------------
[4 3 1]
[4 4 2]
[2 4 4]
[3 4 4]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [ ]:
# complexity: speed = O(n^2), memory = O(n)

# generating an array of 10x3 matrix
matrix = np.random.randint(low=0, high=3, size=(10, 3), dtype=int)
print(matrix)
print("-" * 20)

# find rows of unequal values
boolean_matrix = (matrix == matrix[:, [0]]).all(axis=-1)
ind_array = np.where(~boolean_matrix)[0]
print(ind_array)
print("-" * 20)
print(matrix[ind_array])

[[2 1 1]
 [1 2 0]
 [2 2 2]
 [0 1 1]
 [1 2 0]
 [2 2 0]
 [0 2 1]
 [0 1 2]
 [1 0 0]
 [0 0 0]]
--------------------
[0 1 3 4 5 6 7 8]
--------------------
[[2 1 1]
 [1 2 0]
 [0 1 1]
 [1 2 0]
 [2 2 0]
 [0 2 1]
 [0 1 2]
 [1 0 0]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [30]:
# generate 10x3 matrix
matrix = np.random.randint(low=0, high=3, size=(10, 3), dtype=int)
print(matrix)
print("-" * 20)

result_matrix = np.unique(matrix, axis=0)
print(result_matrix)

[[0 2 2]
 [0 0 2]
 [1 2 1]
 [1 1 0]
 [2 1 1]
 [1 1 2]
 [2 2 1]
 [1 0 2]
 [1 1 0]
 [2 2 0]]
--------------------
[[0 0 2]
 [0 2 2]
 [1 0 2]
 [1 1 0]
 [1 1 2]
 [1 2 1]
 [2 1 1]
 [2 2 0]
 [2 2 1]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

In [32]:
import time

def execute_with_time_measurement(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__}: {end_time - start_time} seconds")
        return result
    return wrapper

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [ ]:
# to see significant difference in time, we need to use large matrix
# for instance, 10000 x 10000
# but python int is up to 2^63 - 1

X = np.random.randint(low=0, high=4, size=(100, 100), dtype=int)

def calculate_product_python(matrix):
    product = 1
    for i in range(len(matrix)):
        if (i < len(matrix[0])) and (matrix[i][i] != 0):
            product *= matrix[i][i]
    return product

def calculate_product_numpy(matrix):
    diagonal = np.diag(matrix)
    return np.prod(diagonal[diagonal != 0])

print(execute_with_time_measurement(calculate_product_python)(X))
print(execute_with_time_measurement(calculate_product_numpy)(X))

calculate_product_python: 4.291534423828125e-05 seconds
296148833645101056
calculate_product_numpy: 3.0040740966796875e-05 seconds
296148833645101056


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [78]:
# to see significant difference in time, we need to use large arrays
# for instance, 10000 and 10000

x = np.random.randint(low=0, high=2, size=3, dtype=int)
y = np.random.randint(low=0, high=2, size=3, dtype=int)
print(x)
print(y)


def check_multiset_python(x, y):
    if len(x) != len(y):
        return False
    x = x.tolist()
    y = y.tolist()

    min_size = min(len(x), len(y))
    for i in range(min_size):
        if x[i] not in y:
            return False
        y.remove(x[i])
    return True


def check_multiset_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))


print(execute_with_time_measurement(check_multiset_python)(x, y))
print(execute_with_time_measurement(check_multiset_numpy)(x, y))

[1 1 0]
[0 1 1]
check_multiset_python: 6.198883056640625e-06 seconds
True
check_multiset_numpy: 3.4809112548828125e-05 seconds
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [131]:
x = np.random.randint(low=0, high=3, size=5, dtype=int)
print(x)
print("-" * 20)


def find_max_element_python(x):
    x = x.tolist()
    candidates = [x[i + 1] for i, val in enumerate(x[:-1]) if val == 0]
    return max(candidates) if candidates else None


def find_max_element_numpy(x):
    ind_zero = np.where(x[:-1] == 0)[0]
    return x[ind_zero + 1].max() if ind_zero.size else None


print(execute_with_time_measurement(find_max_element_python)(x))
print(execute_with_time_measurement(find_max_element_numpy)(x))


[2 2 2 0 2]
--------------------
find_max_element_python: 3.814697265625e-06 seconds
2
find_max_element_numpy: 1.811981201171875e-05 seconds
2


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [159]:
# your code

* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [160]:
# your code

_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [77]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [161]:
# your code

3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [162]:
# your code

4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [163]:
# your code

5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [164]:
# your code

6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [165]:
# your code

7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [166]:
# your code

8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [167]:
# your code