## Numpy Library Exercises

In [1]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [2]:
# let it be an array of 10 random integers between 0 and 10
array = np.random.randint(low=0, high=10, size=10, dtype=int)
print(array)

# change the sign of elements whose values ​​are between 3 and 8
array = np.where((array > 3) & (array < 8), -array, array)
print(array)

[9 9 7 8 3 6 8 7 2 6]
[ 9  9 -7  8  3 -6  8 -7  2 -6]


**2.** Replace the maximum element of a random array with 0

In [3]:
# let it be an array of 10 random integers between 0 and 10
array = np.random.randint(low=0, high=10, size=10, dtype=int)
print(array)

# find the maximum element and replace it with 0
print(array.argmax())
array[array.argmax()] = 0
print(array)

[6 0 0 2 5 9 8 7 0 5]
5
[6 0 0 2 5 0 8 7 0 5]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [4]:
# input a 2-dim array
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)

# construct the direct (cartesian) product of the rows: every combination takes one element per row
grid = np.meshgrid(*array, indexing='ij')
direct_product = np.stack(grid, axis=-1).reshape(-1, len(array))
print(f"\nDirect product:\n{direct_product}")

[[1 2 3]
 [4 5 6]]

Direct product:
[[1 4]
 [1 5]
 [1 6]
 [2 4]
 [2 5]
 [2 6]
 [3 4]
 [3 5]
 [3 6]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [5]:
# complexity: speed = O(n^2), memory = O(n)

# generate two arrays
A = np.random.randint(low=0, high=5, size=(8, 3), dtype=int)
B = np.random.randint(low=0, high=5, size=(2, 2), dtype=int)
print(A)
print(B)

# find rows in A that contain elements from each row in B, regardless of the order of the elements in B
print("-" * 20)
for row in A:
    checked_rows = np.isin(B, row)
    if checked_rows.any(axis=1).all():
        print(row)


[[2 4 3]
 [2 0 1]
 [1 2 2]
 [4 0 1]
 [0 0 4]
 [4 2 1]
 [3 0 0]
 [2 3 1]]
[[1 1]
 [1 1]]
--------------------
[2 0 1]
[1 2 2]
[4 0 1]
[4 2 1]
[2 3 1]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [6]:
# complexity: speed = O(n^2), memory = O(n)

# generating an array of 10x3 matrix
matrix = np.random.randint(low=0, high=3, size=(10, 3), dtype=int)
print(matrix)
print("-" * 20)

# find rows of unequal values
boolean_matrix = (matrix == matrix[:, [0]]).all(axis=-1)
ind_array = np.where(~boolean_matrix)[0]
print(ind_array)
print("-" * 20)
print(matrix[ind_array])

[[1 1 0]
 [1 0 1]
 [1 1 1]
 [0 1 2]
 [1 2 0]
 [1 0 1]
 [2 1 2]
 [2 0 2]
 [2 2 0]
 [1 1 1]]
--------------------
[0 1 3 4 5 6 7 8]
--------------------
[[1 1 0]
 [1 0 1]
 [0 1 2]
 [1 2 0]
 [1 0 1]
 [2 1 2]
 [2 0 2]
 [2 2 0]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [7]:
# generate 10x3 matrix
matrix = np.random.randint(low=0, high=3, size=(10, 3), dtype=int)
print(matrix)
print("-" * 20)

result_matrix = np.unique(matrix, axis=0)
print(result_matrix)

[[0 0 0]
 [1 0 1]
 [1 1 1]
 [1 0 0]
 [2 0 2]
 [0 0 2]
 [2 0 1]
 [0 2 2]
 [1 2 0]
 [2 1 2]]
--------------------
[[0 0 0]
 [0 0 2]
 [0 2 2]
 [1 0 0]
 [1 0 1]
 [1 1 1]
 [1 2 0]
 [2 0 1]
 [2 0 2]
 [2 1 2]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

In [8]:
import time
from functools import wraps

def execute_with_time_measurement(func):

    @wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__}: {end_time - start_time} seconds")
        return result
    return wrapper

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [9]:
# the product over a long diagonal grows way past int64, so both versions accumulate in
# python's arbitrary precision int - otherwise the result silently overflows
X = np.random.randint(low=0, high=4, size=(2000, 2000), dtype=int)

@execute_with_time_measurement
def calculate_product_python(matrix):
    product = 1
    for i in range(len(matrix)):
        if (i < len(matrix[0])) and (matrix[i][i] != 0):
            product *= int(matrix[i][i])
    return product

@execute_with_time_measurement
def calculate_product_numpy(matrix):
    diagonal = np.diag(matrix)
    return np.prod(diagonal[diagonal != 0].astype(object))

print(calculate_product_python(X))
print(calculate_product_numpy(X))

calculate_product_python: 0.0006110668182373047 seconds
2735609494711747957363040169457074954749935029981380981386857431605028721871297590774028982639603725504626750352961991351304140845452478686170973605062600798842613215806122560368504421480720983577608155652924101133094303956306780611440062834082726319350391343510005222771595325278780044608595594619457803536203285813910360910618971347095844236710463790782685394753920617596970035302344036358029312
calculate_product_numpy: 0.00017309188842773438 seconds
2735609494711747957363040169457074954749935029981380981386857431605028721871297590774028982639603725504626750352961991351304140845452478686170973605062600798842613215806122560368504421480720983577608155652924101133094303956306780611440062834082726319350391343510005222771595325278780044608595594619457803536203285813910360910618971347095844236710463790782685394753920617596970035302344036358029312


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [10]:
# large arrays, otherwise the numpy call overhead dominates and the comparison is meaningless
# y is a shuffled copy of x, so the answer is True and neither version can exit early
x = np.random.randint(low=0, high=100, size=100000, dtype=int)
y = np.random.permutation(x)


@execute_with_time_measurement
def check_multiset_python(x, y):
    if len(x) != len(y):
        return False
    return sorted(x.tolist()) == sorted(y.tolist())


@execute_with_time_measurement
def check_multiset_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))


print(check_multiset_python(x, y))
print(check_multiset_numpy(x, y))

check_multiset_python: 0.011213064193725586 seconds
True
check_multiset_numpy: 0.0012202262878417969 seconds
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [11]:
x = np.random.randint(low=0, high=3, size=100000, dtype=int)
print(x)
print("-" * 20)


@execute_with_time_measurement
def find_max_element_python(x):
    x = x.tolist()
    candidates = [x[i + 1] for i, val in enumerate(x[:-1]) if val == 0]
    return max(candidates) if candidates else None


@execute_with_time_measurement
def find_max_element_numpy(x):
    ind_zero = np.where(x[:-1] == 0)[0]
    return x[ind_zero + 1].max() if ind_zero.size else None


print(find_max_element_python(x))
print(find_max_element_numpy(x))


[2 1 1 ... 1 1 0]
--------------------
find_max_element_python: 0.003203868865966797 seconds
2
find_max_element_numpy: 0.0001971721649169922 seconds
2


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
# repeat each drawn value a random number of times, so the vector actually contains runs
X = np.repeat(
    np.random.randint(low=0, high=10, size=100000, dtype=int),
    np.random.randint(low=1, high=4, size=100000, dtype=int),
)

@execute_with_time_measurement
def run_length_encoding_python(x):
    x = x.tolist()
    values, counts = [], []
    for value in x:
        if values and values[-1] == value:
            counts[-1] += 1
        else:
            values.append(value)
            counts.append(1)
    return values, counts

@execute_with_time_measurement
def run_length_encoding_numpy(x):
    starts = np.flatnonzero(np.r_[True, x[1:] != x[:-1]])
    return x[starts], np.diff(np.r_[starts, x.size])


values_python, counts_python = run_length_encoding_python(X)
values_numpy, counts_numpy = run_length_encoding_numpy(X)
print(values_python[:10], counts_python[:10])
print(values_numpy[:10], counts_numpy[:10])
print(np.array_equal(values_python, values_numpy), np.array_equal(counts_python, counts_numpy))

run_length_encoding_python: 0.008178949356079102 seconds
run_length_encoding_numpy: 0.00034999847412109375 seconds
[6, 1, 7, 4, 3, 4, 2, 4, 2, 7] [2, 3, 2, 3, 2, 3, 2, 1, 4, 2]
[6 1 7 4 3 4 2 4 2 7] [2 3 2 3 2 3 2 1 4 2]
True True


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [13]:
from scipy.spatial.distance import cdist

# generate the vectors
X = np.random.randint(low=0, high=10, size=(1000, 1000), dtype=int)
Y = np.random.randint(low=0, high=10, size=(1000, 1000), dtype=int)

@execute_with_time_measurement
def calculate_euclidean_distance_scipy(x, y):
    euclidean_distances = cdist(x, y, metric='euclidean')
    return euclidean_distances

@execute_with_time_measurement
def calculate_euclidean_distance_python(x, y):
    x = x.tolist()
    y = y.tolist()
    euclidean_distances = []
    for a in x:
        row = []
        for b in y:
            # lists don't support a - b; subtract element-wise
            dist = sum((ai - bi) ** 2 for ai, bi in zip(a, b)) ** 0.5
            row.append(dist)
        euclidean_distances.append(row)
    return euclidean_distances

@execute_with_time_measurement
def calculate_euclidean_distance_numpy(x, y):
    # |x - y|^2 = |x|^2 + |y|^2 - 2xy avoids the n x m x d intermediate, which would be
    # several GB here; clipping at 0 guards against small negative rounding errors
    x = x.astype(float)
    y = y.astype(float)
    squared = (x ** 2).sum(axis=1)[:, None] + (y ** 2).sum(axis=1)[None, :] - 2 * (x @ y.T)
    return np.sqrt(np.maximum(squared, 0))


distances_scipy = calculate_euclidean_distance_scipy(X, Y)
distances_python = calculate_euclidean_distance_python(X, Y)
distances_numpy = calculate_euclidean_distance_numpy(X, Y)

print(np.allclose(distances_scipy, distances_numpy))
print(np.allclose(distances_python, distances_numpy))


calculate_euclidean_distance_scipy: 0.17037081718444824 seconds
calculate_euclidean_distance_python: 28.511065006256104 seconds
calculate_euclidean_distance_numpy: 0.007910966873168945 seconds
True
True


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [14]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [2]:
calorie_stats = np.loadtxt("../data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [4]:
CRUNCHIE_MUNCHIES_CALORIES = 60

mean_calories = np.mean(calorie_stats)
print(f"Mean calories: {mean_calories}")

average_calories = round(mean_calories - CRUNCHIE_MUNCHIES_CALORIES, 2)
print(f"Competitors are on average {average_calories} calories higher per serving")

Mean calories: 106.88311688311688
Competitors are on average 46.88 calories higher per serving


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [15]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [16]:
median_calories = np.median(calorie_stats)
print(f"Median calories: {median_calories}")

Median calories: 110.0


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [21]:
# for i in range(101):
#     if np.percentile(calorie_stats_sorted, i) > CRUNCHIE_MUNCHIES_CALORIES:
#         nth_percentile = i
#         break

nth_percentile = np.argmax(
    np.percentile(calorie_stats, np.arange(101)) > CRUNCHIE_MUNCHIES_CALORIES
)
print(f"First method: {nth_percentile}")

nth_percentile = np.round(100 * (calorie_stats < CRUNCHIE_MUNCHIES_CALORIES).mean(), 2)
print(f"Second method: {nth_percentile}")

print(f"60 calories is more than {nth_percentile}% of the data")

First method: 4
Second method: 3.9
60 calories is more than 3.9% of the data


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [20]:
more_calories = (calorie_stats > CRUNCHIE_MUNCHIES_CALORIES).mean()
print(f"60 calories is less than {more_calories * 100:.2f}% of the data")

60 calories is less than 96.10% of the data


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [21]:
calorie_std = np.std(calorie_stats)
print(f"Calorie standard deviation: {calorie_std}")

# the std deviation is 19.36, so that means that the data is spread out over a range of 38.72 (19.36 * 2)

Calorie standard deviation: 19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [22]:
print(f'''
We have the data of other competitiors.
Data: {calorie_stats_sorted}

Mean ({mean_calories:.2f}) is a bit below the median ({median_calories:.2f}), which is a slight left skew

The standard deviation is {calorie_std:.2f}, which means that spread of the data is from {mean_calories - calorie_std:.2f} to {mean_calories + calorie_std:.2f}.
CrunchieMunchies is about {(mean_calories - CRUNCHIE_MUNCHIES_CALORIES) / calorie_std:.2f} standard deviations below the competitor.

CrunchieMunchies is healthier than {more_calories*100:.2f}% of other cereals.
''')


We have the data of other competitiors.
Data: [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]

Mean (106.88) is a bit below the median (110.00), which is a slight left skew

The standard deviation is 19.36, which means that spread of the data is from 87.53 to 126.24.
CrunchieMunchies is about 2.42 standard deviations below the competitor.

CrunchieMunchies is healthier than 96.10% of other cereals.

